-- ============================================
-- LUNARIS V2 Migration
-- Adds missing columns and seeds actual products only
-- Run this in Supabase SQL Editor
-- ============================================

-- ============================================
-- 1. ADD MISSING COLUMNS TO PRODUCTS TABLE
-- ============================================
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS crystal_type TEXT DEFAULT '';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS crystal_effects TEXT[] DEFAULT '{}';

-- ============================================
-- 2. CLEAR EXISTING DATA
-- ============================================
TRUNCATE public.reviews CASCADE;
TRUNCATE public.products CASCADE;
TRUNCATE public.collections CASCADE;
TRUNCATE public.categories CASCADE;

-- ============================================
-- 3. INSERT CATEGORIES (1 active category)
-- ============================================
INSERT INTO public.categories (slug, name, image, product_count) VALUES
('essence-oils', 'Essence Oils', '/Essence oil/Rose Berry.png', 6);

-- ============================================
-- 4. INSERT COLLECTIONS (2 collections)
-- ============================================
INSERT INTO public.collections (slug, name, tagline, description, long_description, image, symbolism, product_count) VALUES
('essence-oil', 'Essence Oil', 'Aromatic chi activation through sacred botanicals', 'Pure essential oil blends infused with crystal energy to harmonize your chakras and elevate your daily rituals.', 'Our Essence Oil collection bridges the worlds of aromatherapy and crystal healing. Each blend is carefully crafted from pure botanical extracts — lavender for crown chakra calm, eucalyptus for throat chakra clarity, and ylang-ylang for heart chakra opening — then charged alongside their corresponding crystals. In yin-yang philosophy, scent is the invisible bridge between body and spirit: yin in its subtlety, yang in its power to transform a space instantly. Use these oils in meditation, bath rituals, or simply to infuse your environment with balanced chi. Every drop carries the intention of alignment.', '/Essence oil/Rose Berry.png', 'Aromatic chi, botanical alchemy, sensory healing. The invisible energy of scent as a pathway to chakra balance.', 6),
('crystal-diffuser', 'Crystal Diffuser', 'Ambient chi purification through crystal mist', 'Crystal-infused diffusers that cleanse your space with harmonized mist, merging stone energy with aromatic vapor.', 'Our Crystal Diffuser collection transforms any room into a sanctuary of balanced energy. Each diffuser is designed with a chamber for genuine crystals — amethyst for spiritual purification, clear quartz for amplification, or rose quartz for heart-centered calm — allowing water vapor to pass through the stones before filling your space with energized mist. In yin-yang philosophy, water is the ultimate yin element: receptive, flowing, and cleansing. When it meets the yang solidity of crystal, the result is a harmonized atmosphere that supports meditation, rest, and inner alignment. Place one in your living space and feel the chi shift.', 'https://images.unsplash.com/photo-1602928321679-560bb453f190?w=1200&h=600&fit=crop&q=80', 'Yin water meets yang stone, spatial purification, ambient harmony. The art of transforming your environment through crystal-charged mist.', 0);

-- ============================================
-- 5. INSERT PRODUCTS (6 Essence Oils)
-- ============================================

-- Rose Berry Essence Oil
INSERT INTO public.products (slug, name, price, compare_at_price, category, collection, gemstone, crystal_type, crystal_effects, symbolic_meaning, short_description, long_description, materials, images, badges, rating, review_count, is_best_seller, is_new, is_giftable, is_active) VALUES
('rose-berry-essence-oil', 'Rose Berry Essence Oil', 58, 78, 'Essence Oils', ARRAY['Essence Oil', 'Love & Harmony'], 'Rose Quartz', 'Rose Quartz', ARRAY['Love', 'Emotional Healing', 'Heart Opening', 'Self-Care'], 'A nurturing blend of rose and berry botanicals, charged with rose quartz to open the heart chakra and invite unconditional love.', 'Crystal-charged aromatherapy oil infused with rose and wild berry essence, paired with rose quartz stones for heart chakra activation.', 'Rose Berry Essence Oil is a luxurious blend of pure rose extract and wild berry botanicals, each drop carefully crafted to harmonize with the heart chakra. The oil is charged alongside hand-selected rose quartz crystals, infusing every application with the gentle vibration of unconditional love. Rose resonates with yin energy — soft, receptive, and nurturing — while the vibrant berry notes carry a subtle yang spark of joy and vitality. Use it as a meditation aid, add it to your bath ritual, or apply to pulse points throughout the day. The included rose quartz stones can be placed in the glass vessel for continuous crystal infusion. A beautiful bridge between aromatherapy and crystal healing.', ARRAY['Pure rose essential oil', 'Wild berry botanical extract', 'Rose quartz crystal chips', 'Glass dropper bottle'], ARRAY['/Essence oil/Rose Berry.png'], ARRAY['new'], 4.8, 42, FALSE, TRUE, TRUE, TRUE);

-- Chocolate Gourmet Essence Oil
INSERT INTO public.products (slug, name, price, compare_at_price, category, collection, gemstone, crystal_type, crystal_effects, symbolic_meaning, short_description, long_description, materials, images, badges, rating, review_count, is_best_seller, is_new, is_giftable, is_active) VALUES
('chocolate-gourmet-essence-oil', 'Chocolate Gourmet Essence Oil', 62, 82, 'Essence Oils', ARRAY['Essence Oil'], 'Smoky Quartz', 'Smoky Quartz', ARRAY['Grounding', 'Comfort', 'Stress Relief', 'Warmth'], 'A grounding blend of rich cacao and warm spice, charged with smoky quartz to anchor your root chakra and wrap you in comfort.', 'Crystal-charged aromatherapy oil infused with cacao and hazelnut essence, paired with smoky quartz stones for root chakra grounding.', 'Chocolate Gourmet Essence Oil is a decadent blend of pure cacao absolute, warm hazelnut, and a hint of vanilla bean. Each bottle is charged alongside hand-selected smoky quartz crystals, grounding every drop in the stabilizing energy of the root chakra. Cacao has been revered since ancient times as a sacred heart opener, while smoky quartz dissolves stress and negativity. Together they create a deeply comforting ritual — perfect for evening meditation, self-care baths, or moments when you need to feel held by the earth. The included smoky quartz chips can be added to your crystal vessel for continuous infusion.', ARRAY['Pure cacao absolute', 'Hazelnut botanical extract', 'Vanilla bean essence', 'Smoky quartz crystal chips', 'Glass dropper bottle'], ARRAY['/Essence oil/Chocolate Gourmet.png'], ARRAY['new'], 4.7, 31, FALSE, TRUE, TRUE, TRUE);

-- Citrus Mint Essence Oil
INSERT INTO public.products (slug, name, price, compare_at_price, category, collection, gemstone, crystal_type, crystal_effects, symbolic_meaning, short_description, long_description, materials, images, badges, rating, review_count, is_best_seller, is_new, is_giftable, is_active) VALUES
('citrus-mint-essence-oil', 'Citrus Mint Essence Oil', 55, 72, 'Essence Oils', ARRAY['Essence Oil'], 'Citrine', 'Citrine', ARRAY['Energy', 'Clarity', 'Joy', 'Manifestation'], 'A vibrant blend of citrus and fresh mint, charged with citrine to ignite the solar plexus chakra and awaken joyful energy.', 'Crystal-charged aromatherapy oil infused with lemon, orange, and peppermint essence, paired with citrine stones for solar plexus activation.', 'Citrus Mint Essence Oil bursts with the uplifting energy of sun-ripened lemon, sweet orange, and crisp peppermint. Charged alongside golden citrine crystals, this blend activates the solar plexus chakra — your center of confidence, willpower, and radiant joy. Citrus carries pure yang energy: bright, expansive, and forward-moving, while mint clears stagnant chi and sharpens focus. Use it as a morning ritual to set your intention, diffuse it during work for sustained clarity, or apply to pulse points before any situation that calls for your boldest self. The included citrine chips amplify abundance consciousness with every use.', ARRAY['Pure lemon essential oil', 'Sweet orange extract', 'Peppermint essential oil', 'Citrine crystal chips', 'Glass dropper bottle'], ARRAY['/Essence oil/Citrus mint.png'], ARRAY['new'], 4.9, 56, FALSE, TRUE, TRUE, TRUE);

-- Ocean Vetiver Essence Oil
INSERT INTO public.products (slug, name, price, compare_at_price, category, collection, gemstone, crystal_type, crystal_effects, symbolic_meaning, short_description, long_description, materials, images, badges, rating, review_count, is_best_seller, is_new, is_giftable, is_active) VALUES
('ocean-vetiver-essence-oil', 'Ocean Vetiver Essence Oil', 60, 78, 'Essence Oils', ARRAY['Essence Oil'], 'Aquamarine', 'Aquamarine', ARRAY['Calm', 'Communication', 'Purification', 'Flow'], 'An oceanic blend of vetiver and sea minerals, charged with aquamarine to open the throat chakra and invite the flow of calm communication.', 'Crystal-charged aromatherapy oil infused with vetiver and ocean botanicals, paired with aquamarine stones for throat chakra purification.', 'Ocean Vetiver Essence Oil captures the serene power of the sea — deep vetiver root grounded by oceanic mineral notes and a whisper of sea grass. Charged alongside pale blue aquamarine crystals, this blend resonates with the throat chakra, the energy center of truthful expression and fluid communication. Vetiver is the ultimate yin essence: deep, earthy, and calming, while aquamarine channels the ocean''s endless flow. Together they create a profound sense of peace that settles the nervous system and opens the voice. Ideal for meditation near water, pre-speaking rituals, or any time you need to return to your deepest calm.', ARRAY['Pure vetiver essential oil', 'Sea mineral extract', 'Sea grass botanical essence', 'Aquamarine crystal chips', 'Glass dropper bottle'], ARRAY['/Essence oil/Ocean Vetiver.png'], ARRAY['new'], 4.8, 38, FALSE, TRUE, TRUE, TRUE);

-- Oud Wood Essence Oil
INSERT INTO public.products (slug, name, price, compare_at_price, category, collection, gemstone, crystal_type, crystal_effects, symbolic_meaning, short_description, long_description, materials, images, badges, rating, review_count, is_best_seller, is_new, is_giftable, is_active) VALUES
('oud-wood-essence-oil', 'Oud Wood Essence Oil', 72, 95, 'Essence Oils', ARRAY['Essence Oil'], 'Amethyst', 'Amethyst', ARRAY['Spiritual Awareness', 'Wisdom', 'Protection', 'Meditation'], 'A sacred blend of ancient oud and forest botanicals, charged with amethyst to activate the third eye and crown chakras for deep spiritual connection.', 'Crystal-charged aromatherapy oil infused with rare oud wood and forest moss, paired with amethyst stones for crown chakra meditation.', 'Oud Wood Essence Oil is our most mystical blend, built around the legendary agarwood — one of the rarest and most prized aromatics in the world. Deep oud is layered with forest moss, ancient cedar, and a breath of frankincense, then charged alongside purple amethyst crystals that resonate with the third eye and crown chakras. Oud has been used in spiritual ceremonies across cultures for millennia, valued for its ability to quiet the mind and open the gateway to higher consciousness. This oil is crafted for those who seek depth in their practice — use it during meditation, energy healing sessions, or as an evening ritual to close the day with wisdom and peace.', ARRAY['Rare oud wood absolute', 'Forest moss extract', 'Cedar essential oil', 'Frankincense resin essence', 'Amethyst crystal chips', 'Glass dropper bottle'], ARRAY['/Essence oil/Oud Wood.png'], ARRAY['new'], 4.9, 27, FALSE, TRUE, TRUE, TRUE);

-- White Musk Essence Oil
INSERT INTO public.products (slug, name, price, compare_at_price, category, collection, gemstone, crystal_type, crystal_effects, symbolic_meaning, short_description, long_description, materials, images, badges, rating, review_count, is_best_seller, is_new, is_giftable, is_active) VALUES
('white-musk-essence-oil', 'White Musk Essence Oil', 58, 75, 'Essence Oils', ARRAY['Essence Oil'], 'Clear Quartz', 'Clear Quartz', ARRAY['Clarity', 'Amplification', 'Purity', 'Harmony'], 'A pure and ethereal blend of white musk and cotton flower, charged with clear quartz to amplify all chakras and create a sanctuary of clean energy.', 'Crystal-charged aromatherapy oil infused with white musk and cotton blossom, paired with clear quartz stones for full-spectrum chakra amplification.', 'White Musk Essence Oil is the purest expression of our collection — a clean, luminous blend of ethically sourced white musk, soft cotton flower, and a touch of white tea. Charged alongside clear quartz, the master healer crystal that amplifies the energy of all seven chakras simultaneously. White musk embodies the balance point of yin and yang: neither heavy nor light, neither warm nor cool, but perfectly centered. This makes it the ideal everyday essence — one that creates a clean energetic field around you without imposing any particular mood. Use it as your daily signature scent, layer it with other oils in our collection, or diffuse it to purify your living space.', ARRAY['Ethically sourced white musk', 'Cotton flower extract', 'White tea essence', 'Clear quartz crystal chips', 'Glass dropper bottle'], ARRAY['/Essence oil/White Musk.png'], ARRAY['new'], 4.8, 45, FALSE, TRUE, TRUE, TRUE);

-- ============================================
-- 6. INSERT REVIEWS (5 reviews for essence oils)
-- ============================================
INSERT INTO public.reviews (product_id, author, rating, text, verified, created_at) VALUES
((SELECT id FROM public.products WHERE slug = 'rose-berry-essence-oil'), 'Sarah M.', 5, 'The Rose Berry oil is absolutely divine. The scent is soft and nurturing, perfect for my evening meditation. I can feel the rose quartz energy every time I use it.', TRUE, '2026-03-15T00:00:00Z'),
((SELECT id FROM public.products WHERE slug = 'oud-wood-essence-oil'), 'James T.', 5, 'Oud Wood is incredible. The depth and richness of the scent is unlike anything I''ve experienced. It truly transforms my meditation space.', TRUE, '2026-03-10T00:00:00Z'),
((SELECT id FROM public.products WHERE slug = 'citrus-mint-essence-oil'), 'Michelle L.', 4, 'Love the Citrus Mint oil — it''s my go-to morning ritual now. Wakes me up and keeps me focused throughout the day. Great quality.', TRUE, '2026-03-05T00:00:00Z'),
((SELECT id FROM public.products WHERE slug = 'white-musk-essence-oil'), 'Elena G.', 5, 'White Musk is my daily signature. It''s clean, balanced, and somehow makes every space feel more peaceful. Layering it with Rose Berry is magical.', TRUE, '2026-02-20T00:00:00Z'),
((SELECT id FROM public.products WHERE slug = 'ocean-vetiver-essence-oil'), 'David K.', 5, 'Ocean Vetiver brings a sense of deep calm. The aquamarine crystal pairing is perfect — I use it before every important meeting.', TRUE, '2026-02-15T00:00:00Z');

-- ============================================
-- DONE!
-- Next step: Run supabase-storage-setup.sql to create the image upload bucket
-- ============================================
