-- ============================================
-- LUNARIS E-Commerce Seed Data
-- Run this in Supabase SQL Editor after schema.sql
-- ============================================

-- ============================================
-- INSERT CATEGORIES (6 total)
-- ============================================
INSERT INTO public.categories (slug, name, image, product_count) VALUES
('bracelets', 'Bracelets', 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=600&fit=crop&q=80', 5),
('necklaces', 'Necklaces', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=600&fit=crop&q=80', 5),
('earrings', 'Earrings', 'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=600&h=600&fit=crop&q=80', 5),
('rings', 'Rings', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&h=600&fit=crop&q=80', 3),
('jewelry-sets', 'Jewelry Sets', 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=600&h=600&fit=crop&q=80', 2),
('home-decor', 'Home Decor', 'https://images.unsplash.com/photo-1615486511262-c7b5e1ab9f11?w=600&h=600&fit=crop&q=80', 1);

-- ============================================
-- INSERT COLLECTIONS (7 total)
-- ============================================
INSERT INTO public.collections (slug, name, tagline, description, long_description, image, symbolism, product_count) VALUES
('protection', 'Protection', 'Guardianship for your spiritual path', 'Intentional pieces designed to support grounding, resilience, and energetic boundaries.', 'Our Protection collection honors ancient traditions of spiritual guardianship. Each piece is crafted with stones and symbols that have been treasured across cultures for their grounding and protective qualities. From black tourmaline to protective eye symbols, these pieces support you in maintaining clear energetic boundaries while staying rooted in your truth. Perfect for anyone navigating transitions, managing stress, or simply seeking to strengthen their spiritual foundation. Protection is not about fear—it''s about standing firmly in your power.', 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=1200&h=600&fit=crop&q=80', 'Strength, grounding, resilience. The ability to maintain your center regardless of external circumstances.', 6),
('love-harmony', 'Love & Harmony', 'Intention for the heart and soul', 'Pieces celebrating compassion, connection, and inner alignment.', 'Love in the LUNARIS philosophy extends beyond romance—it encompasses self-compassion, connection to all beings, and the harmony that emerges when we lead with our hearts. This collection features rose quartz, tourmaline, aquamarine, and other heart-centered stones. Whether you''re deepening a relationship, cultivating self-love, or simply seeking more peace in your daily life, these pieces serve as gentle reminders of your capacity for compassion. The harmony they inspire radiates outward, touching everyone you encounter.', 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=1200&h=600&fit=crop&q=80', 'Compassion, connection, alignment. The frequency of love expressed through intention and beauty.', 8),
('prosperity', 'Prosperity', 'Abundance consciousness in wearable form', 'Citrine, pyrite, jade, and amber for attracting meaningful abundance.', 'Prosperity is about more than material wealth—it''s about cultivating abundance consciousness in all forms: time, relationships, creativity, health, and resources. This collection features stones traditionally associated with manifestation and gratitude. Citrine''s warm golden light, pyrite''s reflective gleam, jade''s steady calm, and amber''s ancient wisdom all support an expansive mindset. Wear these pieces as daily anchors for prosperity consciousness, reminding yourself that you are worthy of a rich and full life.', 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=1200&h=600&fit=crop&q=80', 'Manifestation, gratitude, worthiness. The knowledge that abundance begins with consciousness and intention.', 4),
('birthstones', 'Birthstones', 'Aligned with your celestial identity', 'Traditional birthstone pieces celebrating your month and cosmic connection.', 'Birthstones connect us to the cosmic moment of our arrival—a spiritual fingerprint of sorts. Each month carries its own energetic signature, represented by stones treasured for their unique qualities. Whether you''re drawn to amethyst for its clarifying calm, pearl for its timeless wisdom, or any of the other sacred stones, a birthstone piece becomes a deeply personal talisman. Wear your birthstone as a connection to your essence, or gift it as a way of honoring someone''s unique place in the cosmos.', 'https://images.unsplash.com/photo-1602519093515-7e7ca91a27e3?w=1200&h=600&fit=crop&q=80', 'Identity, destiny, cosmic connection. Your personal celestial signature made wearable.', 3),
('evil-eye', 'Evil Eye', 'Ancient protection across cultures', 'The watchful protection symbol honored in Mediterranean and Eastern traditions.', 'The evil eye appears in protective traditions across the Mediterranean, Middle East, and Asia—a symbol of divine watchfulness and protection against negativity. This collection honors that ancient wisdom while transcending cultural boundaries. Each piece combines the traditional evil eye symbol with complementary protective stones, creating modern expressions of timeless guardianship. Wear an evil eye piece as a talisman against negativity, as a symbol of spiritual sight, or simply as a beautiful reminder to maintain clear vision about your path and purpose.', 'https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=1200&h=600&fit=crop&q=80', 'Spiritual sight, protection, divine watchfulness. The awareness that see clearly and act from integrity.', 3),
('tree-of-life', 'Tree of Life', 'Growth rooted in wisdom', 'The universal symbol of connection, ancestry, and spiritual growth.', 'The Tree of Life appears across spiritual traditions as a symbol of connection—roots in ancestral wisdom, trunk in the present moment, branches reaching toward possibility. This collection celebrates that archetypal symbol through contemporary craftsmanship. Whether you''re meditating on your own growth journey, honoring your lineage, or simply seeking to remember your place in the greater whole, a Tree of Life piece becomes a constant meditation. Wear it through seasons of change as a reminder that growth is natural, that you are supported by those who came before, and that your highest self is always reaching upward.', 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=1200&h=600&fit=crop&q=80', 'Growth, connection, ancestry. The knowledge that you are rooted in wisdom while reaching toward your potential.', 2),
('red-string', 'Red String', 'Destiny and divine connection', 'Ancient symbol of the invisible threads that bind meaningful encounters.', 'Across cultures, the red string symbolizes destiny—the invisible thread connecting souls meant to meet. Worn as a talisman of fate and divine protection, the red string reminds us that our most meaningful connections are never accidents. This collection honors that beautiful tradition with pieces that combine the red thread with gemstones that support connection, courage, and clarity. Wear a red string piece as a celebration of destiny, as protection during journeys, or as a gift symbolizing an unbreakable bond with someone you love.', 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=1200&h=600&fit=crop&q=80', 'Destiny, connection, protection. The knowledge that meaningful encounters are woven into your path.', 1);

-- ============================================
-- INSERT PRODUCTS (20 total)
-- ============================================
INSERT INTO public.products (slug, name, price, compare_at_price, category, collection, gemstone, symbolic_meaning, short_description, long_description, materials, images, badges, rating, review_count, is_best_seller, is_new, is_giftable, is_active) VALUES

('moonlit-guardian-bracelet', 'Moonlit Guardian Bracelet', 128.00, 168.00, 'Bracelets', ARRAY['Protection', 'Love & Harmony'], 'Black Tourmaline', 'Protection and grounding energy. A steadfast companion for navigating life''s complexities.', 'Sterling silver bracelet with black tourmaline beads, designed for grounding and inner clarity.', 'Crafted with intention, the Moonlit Guardian combines the protective properties of black tourmaline with the elegant simplicity of sterling silver. Each bead is hand-selected for its natural patterns and energy. This bracelet serves as a meaningful reminder to stay grounded in your truth, no matter what surrounds you. Perfect for daily wear and layering with intention.', ARRAY['Sterling Silver', 'Black Tourmaline', 'Elastic cord'], ARRAY['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&h=800&fit=crop&q=80'], ARRAY['bestseller', 'bestseller-2024'], 4.8, 247, TRUE, FALSE, TRUE, TRUE),

('celestial-shield-pendant', 'Celestial Shield Pendant', 198.00, 248.00, 'Necklaces', ARRAY['Protection', 'Evil Eye'], 'Lapis Lazuli', 'Divine protection and inner vision. A sentinel of wisdom and truth.', '14K gold-plated pendant featuring lapis lazuli and protective symbolism, handcrafted with celestial details.', 'The Celestial Shield is an intentional piece designed to inspire confidence and spiritual clarity. Deep lapis lazuli evokes the night sky and inner knowing, while the geometric protection symbol is delicately etched into the frame. Suspended on a 18-inch adjustable chain, this pendant works as both a statement piece and a subtle daily reminder of your inner strength. The timeless lapis stone connects you to ancient wisdom traditions across cultures.', ARRAY['14K Gold-plated sterling silver', 'Lapis Lazuli', 'Gold chain'], ARRAY['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1515562141589-67f0d569b2d5?w=800&h=800&fit=crop&q=80'], ARRAY['new'], 4.9, 89, FALSE, TRUE, TRUE, TRUE),

('whisper-of-rose-quartz-earrings', 'Whisper of Rose Quartz Earrings', 92.00, NULL, 'Earrings', ARRAY['Love & Harmony'], 'Rose Quartz', 'Unconditional love and compassion. A gentle reminder to lead with your heart.', 'Delicate rose quartz sphere earrings with 14K gold vermeil hooks, crafted for everyday elegance.', 'These understated earrings celebrate the timeless beauty of rose quartz. Each pale pink sphere is cut and polished to catch light softly, creating a gentle presence at the ear. Rose quartz, known as the stone of unconditional love, is worn as a daily practice of compassion—first toward yourself, then extending outward. The 14K gold vermeil hooks ensure comfort and durability for daily wear. A meaningful gift for yourself or someone you cherish.', ARRAY['Rose Quartz', '14K Gold Vermeil', 'Surgical steel posts'], ARRAY['https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&h=800&fit=crop&q=80'], ARRAY[]::TEXT[], 4.7, 156, FALSE, FALSE, TRUE, TRUE),

('eternal-bond-ring', 'Eternal Bond Ring', 248.00, 298.00, 'Rings', ARRAY['Love & Harmony'], 'Diamond (lab-created)', 'Enduring connection and commitment. A promise worn in clarity and light.', 'Minimalist engagement or commitment ring featuring lab-created diamond, sustainably crafted.', 'The Eternal Bond ring distills commitment to its essence: clarity, brilliance, and timelessness. Featuring an ethically sourced lab-created diamond set in sustainable platinum-plated silver, this ring honors the promise of forever while respecting the earth. The clean, geometric band allows the stone''s light to speak. Whether worn as an engagement ring or a personal symbol of self-commitment, it carries meaning as intentional as the moment it was chosen. Available in sizes 4-12.', ARRAY['Platinum-plated sterling silver', 'Lab-created diamond (0.75ct)', 'Sustainable sourcing'], ARRAY['https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&h=800&fit=crop&q=80'], ARRAY['bestseller'], 4.9, 312, TRUE, FALSE, TRUE, TRUE),

('golden-abundance-bracelet', 'Golden Abundance Bracelet', 156.00, 198.00, 'Bracelets', ARRAY['Prosperity'], 'Citrine', 'Prosperity and manifested intention. A golden reminder of your innate worth.', 'Warm citrine and pyrite bracelet with 24K gold accents, designed to invite intentional abundance.', 'Radiant citrine pairs with reflective pyrite in this prosperity-focused bracelet, creating a visual and energetic blend of warmth and abundance. Each stone is hand-selected for its natural variations and beauty. The delicate 24K gold spacers catch light like small promises of prosperity consciousness. Wear this as a daily reminder that abundance—in all its forms—begins with intention and gratitude. The adjustable design fits comfortably on any wrist.', ARRAY['Citrine', 'Pyrite', '24K Gold plating', 'Elastic cord', 'Sterling silver spacers'], ARRAY['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=800&h=800&fit=crop&q=80'], ARRAY['new'], 4.6, 94, FALSE, TRUE, TRUE, TRUE),

('midnight-obsidian-necklace', 'Midnight Obsidian Necklace', 175.00, NULL, 'Necklaces', ARRAY['Protection'], 'Black Obsidian', 'Deep protection and shadow work. Safe passage through life''s darkest passages.', 'Polished volcanic glass obsidian pendant on leather cord, a striking grounding piece.', 'Born from ancient volcanic activity, black obsidian carries the earth''s protection within its glossy depths. This necklace features a single polished pendant suspended on a soft leather cord, allowing the stone''s natural patterns to be the focal point. Obsidian traditionally serves as a guardian stone, shielding against negativity while encouraging grounded clarity. The minimalist presentation makes it equally at home in boardrooms or meditation spaces. An intentional piece for anyone seeking to cultivate resilience and inner stability.', ARRAY['Black Obsidian', 'Leather cord', 'Sterling silver clasp'], ARRAY['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1515562141589-67f0d569b2d5?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&h=800&fit=crop&q=80'], ARRAY[]::TEXT[], 4.7, 128, FALSE, FALSE, TRUE, TRUE),

('serenity-tree-of-life-pendant', 'Serenity Tree of Life Pendant', 142.00, 178.00, 'Necklaces', ARRAY['Tree of Life'], 'Mixed gemstones', 'Connection, growth, and ancestral wisdom. Roots in the past, branches toward the future.', 'Handcrafted tree of life pendant with mixed gemstone leaves, symbolizing connection and growth.', 'The Tree of Life represents humanity''s place within nature and the cosmos. This pendant brings that ancient symbol into your daily life with delicate craftsmanship. Each ''leaf'' is cut from a different gemstone—amethyst, rose quartz, citrine, and turquoise—creating a prism of natural beauty. The tree''s trunk and branches are hand-twisted in 14K gold-plated silver. Wear it as a meditation on your own growth, your connection to all living things, and your place in the greater whole. A meaningful piece that resonates across spiritual traditions.', ARRAY['14K Gold-plated sterling silver', 'Amethyst', 'Rose Quartz', 'Citrine', 'Turquoise', 'Adjustable chain'], ARRAY['https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1515562141589-67f0d569b2d5?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&h=800&fit=crop&q=80'], ARRAY['bestseller'], 4.8, 203, TRUE, FALSE, TRUE, TRUE),

('crimson-thread-of-fate-bracelet', 'Crimson Thread of Fate Bracelet', 68.00, NULL, 'Bracelets', ARRAY['Red String'], 'Carnelian', 'Destiny and divine connection. The invisible thread that binds all meaningful encounters.', 'Traditional red string bracelet with carnelian bead, inspired by ancient protective traditions.', 'Rooted in protection traditions spanning cultures, the red thread symbolizes the invisible connections between souls destined to meet. This version weaves a single carnelian bead—a stone of vitality and courage—into a simple, elegant cord. Wear it as a talisman of destiny, as a reminder that meaningful encounters are never accidents. The adjustable design makes it easy to share or gift. A subtle, powerful piece grounded in ancient wisdom and modern intention.', ARRAY['Red silk cord', 'Carnelian', 'Adjustable closure'], ARRAY['https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop&q=80'], ARRAY[]::TEXT[], 4.5, 178, FALSE, FALSE, TRUE, TRUE),

('aurora-borealis-earrings', 'Aurora Borealis Earrings', 118.00, 148.00, 'Earrings', ARRAY['Love & Harmony'], 'Labradorite', 'Magic and transformation. A reminder that light exists within all darkness.', 'Shimmering labradorite earrings featuring protective shimmer, 14K gold-plated setting.', 'Like the northern lights dancing across winter skies, labradorite captures light in unexpected ways. These earrings celebrate the stone''s characteristic play-of-color—called labradorescence—which shifts and shimmers with every movement. Beyond their visual magic, labradorites are traditionally worn for transformation and protection during times of change. The 14K gold-plated setting grounds the ethereal stone in warmth. Perfect for anyone navigating transitions and seeking to remember their inner light. Wear them as a daily reminder that transformation is beautiful.', ARRAY['Labradorite', '14K Gold-plated sterling silver', 'Surgical steel posts'], ARRAY['https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&h=800&fit=crop&q=80'], ARRAY['new'], 4.7, 67, FALSE, TRUE, TRUE, TRUE),

('sacred-eye-charm-necklace', 'Sacred Eye Charm Necklace', 95.00, NULL, 'Necklaces', ARRAY['Evil Eye', 'Protection'], 'Evil eye enamel and lapis', 'Watchful protection and spiritual sight. Guardian of your path and intention.', 'Traditional evil eye necklace with lapis accents, a symbol of protection across cultures.', 'The evil eye appears in protective traditions across Mediterranean, Middle Eastern, and Asian cultures—a symbol of divine watchfulness. This necklace honors that ancient wisdom with an enamel evil eye centered in deep lapis lazuli. The combination invokes both spiritual sight and protective presence. Wear it as a talisman against negativity and as a reminder to cultivate clear vision in your own life. The pendant hangs on a delicate gold chain, making it wearable across any style. A meaningful piece with roots deeper than trend.', ARRAY['Enamel', 'Lapis Lazuli', '14K Gold-plated sterling silver', 'Gold chain'], ARRAY['https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=800&h=800&fit=crop&q=80'], ARRAY['bestseller'], 4.8, 421, TRUE, FALSE, TRUE, TRUE),

('lotus-bloom-ring', 'Lotus Bloom Ring', 175.00, 218.00, 'Rings', ARRAY['Love & Harmony'], 'Pink tourmaline', 'Spiritual awakening and pure enlightenment. Rising from stillness into your fullest expression.', 'Delicate lotus-shaped ring with pink tourmaline, symbolizing spiritual growth and purity.', 'The lotus rises from muddy waters to bloom in pure sunlight—a universal symbol of transformation and spiritual awakening. This ring captures that journey in miniature. Pink tourmaline at the flower''s heart represents compassion and heart opening. The lotus petals are hand-carved in sterling silver, creating an almost sculptural quality. Wear it as a reminder of your capacity for growth, your resilience, and your ability to bloom regardless of circumstances. A meaningful piece for personal transformation or a gift for someone beginning their spiritual journey.', ARRAY['Sterling Silver', 'Pink Tourmaline', 'Hand-carved petals'], ARRAY['https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&h=800&fit=crop&q=80'], ARRAY['new'], 4.6, 74, FALSE, TRUE, TRUE, TRUE),

('starlight-amethyst-bracelet', 'Starlight Amethyst Bracelet', 104.00, NULL, 'Bracelets', ARRAY['Birthstones', 'Love & Harmony'], 'Amethyst', 'Clarity, calm, and spiritual awareness. A gateway to inner peace and intuition.', 'Purple amethyst bracelet with sterling silver accents, designed for daily spiritual practice.', 'Amethyst, the stone of clarity and calm, has been treasured across cultures as a pathway to deeper awareness. This bracelet pairs polished amethyst spheres with delicate sterling silver details, creating an elegant piece suitable for meditation, work, or daily wear. The cool purple tones are simultaneously grounding and elevating. Amethyst''s traditional association with intuition makes this piece particularly meaningful for anyone seeking to strengthen their inner knowing. Wear it as a daily practice of stillness, or gift it to someone navigating a period of transformation.', ARRAY['Amethyst', 'Sterling Silver', 'Elastic cord', 'Adjustable fit'], ARRAY['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&h=800&fit=crop&q=80'], ARRAY['bestseller'], 4.8, 289, TRUE, FALSE, TRUE, TRUE),

('ocean-embrace-earrings', 'Ocean''s Embrace Earrings', 138.00, 178.00, 'Earrings', ARRAY['Love & Harmony'], 'Aquamarine', 'Calm, clarity, and inner peace. The serene depth of water reflecting sky.', 'Soft aquamarine earrings with 14K gold setting, evoking oceanic tranquility and flow.', 'Aquamarine, named for the sea itself, carries the ocean''s tranquil essence. These earrings feature pale blue stones that shift with light, evoking water depths and endless horizons. Aquamarine is traditionally worn for clear communication and emotional clarity—qualities that emerge when we align with water''s flowing acceptance. The 14K gold-plated setting provides warmth against the cool blue, creating visual balance. A versatile piece that works for everyday wear or as a thoughtful gift for someone seeking more flow and ease in their life.', ARRAY['Aquamarine', '14K Gold-plated sterling silver', 'Surgical steel posts'], ARRAY['https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&h=800&fit=crop&q=80'], ARRAY['new'], 4.7, 51, FALSE, TRUE, TRUE, TRUE),

('temple-of-light-jewelry-set', 'Temple of Light Jewelry Set', 268.00, 328.00, 'Jewelry Sets', ARRAY['Love & Harmony', 'Protection'], 'Mixed gemstones', 'Complete spiritual alignment across body and spirit. A unified practice of presence.', 'Coordinated set including necklace, bracelet, and earrings with complementary gemstones.', 'Designed for those who practice intentional living across every dimension of their day, the Temple of Light set brings cohesive energy to your spiritual practice. The set includes a rose quartz heart pendant, corresponding rose quartz and turquoise bracelet, and matching earrings—each piece thoughtfully chosen to work in harmony. Rose quartz centers you in love, while turquoise supports authentic communication and peaceful presence. Wear together for unified intention, or mix and match as needed. A complete offering for someone deepening their spiritual practice, or a luxurious gift for milestone moments.', ARRAY['Rose Quartz', 'Turquoise', '14K Gold-plated sterling silver', 'Adjustable chains and cords'], ARRAY['https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=800&h=800&fit=crop&q=80'], ARRAY['bestseller'], 4.9, 156, TRUE, FALSE, TRUE, TRUE),

('amber-solstice-necklace', 'Amber Solstice Necklace', 165.00, 208.00, 'Necklaces', ARRAY['Prosperity', 'Birthstones'], 'Baltic Amber', 'Warmth, ancient wisdom, and the turning of seasons. Earth''s golden memory.', 'Genuine Baltic amber pendant capturing ancient warmth, set in oxidized silver.', 'Amber holds the earth''s memory—fossilized resin that glowed with warmth millions of years ago. This necklace features genuine Baltic amber, each piece unique with natural inclusions and warm honey tones. Set in oxidized sterling silver that echoes amber''s antiquity, the pendant becomes a meditation on time, transformation, and the persistence of beauty. Amber traditionally connects to prosperity consciousness and ancient wisdom. Wear it as a reminder that all beautiful things take time, and that you carry within you the resilience of ancient earth. A conversation piece with soul.', ARRAY['Genuine Baltic Amber', 'Oxidized sterling silver', 'Silver chain'], ARRAY['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1515562141589-67f0d569b2d5?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=800&fit=crop&q=80'], ARRAY[]::TEXT[], 4.6, 82, FALSE, FALSE, TRUE, TRUE),

('spirit-quartz-tower-home-decor', 'Spirit Quartz Tower', 58.00, 78.00, 'Home Decor', ARRAY['Prosperity', 'Love & Harmony'], 'Spirit Quartz', 'Collective harmony and spiritual elevation. Many voices unified in light.', 'Polished spirit quartz tower for home or altar, naturally clustered crystal form.', 'Spirit quartz—also called cactus quartz—grows in unique clustered formations, where countless small crystals surround a central point. This natural geometry symbolizes community, unity, and collective consciousness. Each tower is naturally formed and polished to reveal its delicate violet and clear crystal matrix. Ideal for a bedside table, meditation altar, or work desk, it silently radiates harmony. Spirit quartz traditionally supports group energy and social connection—perfect for shared spaces or as a gift celebrating community. A beautiful conversation piece that brings both aesthetic beauty and intentional energy to your environment.', ARRAY['Natural Spirit Quartz', 'Hand-polished', 'Naturally formed'], ARRAY['https://images.unsplash.com/photo-1615486511262-c7b5e1ab9f11?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1602519093515-7e7ca91a27e3?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1615486511262-c7b5e1ab9f11?w=800&h=800&fit=crop&q=80'], ARRAY['new'], 4.7, 43, FALSE, TRUE, TRUE, TRUE),

('harmony-jade-bracelet', 'Harmony Jade Bracelet', 148.00, 188.00, 'Bracelets', ARRAY['Love & Harmony', 'Prosperity'], 'Jade', 'Balance, peace, and prosperity. The stone of gentle, steady alignment.', 'Luminous jade bangle bracelet with minimalist sterling silver details.', 'Jade has held sacred significance across Asian cultures for thousands of years—a stone of luck, balance, and inner harmony. This bangle features jewel-tone jade (a deeper, more valuable variety) with subtle sterling silver accents that don''t overwhelm the stone''s natural beauty. The smooth, rounded form invites touch and meditation. Whether worn for its traditional association with prosperity or simply for the grounding calm it inspires, this bracelet becomes part of your daily ritual. The timeless design transcends trend, making it equally appropriate as an heirloom gift or a personal investment in peace.', ARRAY['Jade (natural)', 'Sterling Silver', 'Smooth bangle form'], ARRAY['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop&q=80'], ARRAY['bestseller'], 4.8, 195, TRUE, FALSE, TRUE, TRUE),

('phoenix-rising-ring', 'Phoenix Rising Ring', 218.00, 268.00, 'Rings', ARRAY['Protection', 'Love & Harmony'], 'Garnet', 'Rebirth and inner strength. Rising renewed from every challenge.', 'Statement ring featuring deep red garnet with phoenix motif, symbolizing resilience.', 'The phoenix has inspired hope across mythologies—the bird that rises anew from ashes, stronger and more radiant. This ring honors that archetype with a deep, glowing garnet set in a frame that echoes phoenix wings in flight. Garnet traditionally supports courage and vitality, making this piece both symbolically powerful and visually striking. Perfect for marking transformations, celebrating survivorship, or simply reminding yourself of your resilience on difficult days. A statement ring for anyone who has risen and knows they can rise again.', ARRAY['Sterling Silver', 'Garnet (deep red)', 'Hand-carved phoenix motif'], ARRAY['https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&h=800&fit=crop&q=80'], ARRAY['new'], 4.7, 68, FALSE, TRUE, TRUE, TRUE),

('pearl-of-wisdom-earrings', 'Pearl of Wisdom Earrings', 124.00, 164.00, 'Earrings', ARRAY['Birthstones', 'Love & Harmony'], 'Freshwater Pearl', 'Inner wisdom and authentic beauty. Truth formed through time and pressure.', 'Luminous freshwater pearl earrings with 14K gold vermeil, elegant and timeless.', 'Pearls emerge from depth and irritation, transformed by time into objects of profound beauty. A perfect metaphor for human wisdom—crafted through experience and challenge. These earrings feature quality freshwater pearls with subtle variations that speak to their natural origin. Each pearl is unique, making these a deeply personal piece. The 14K gold vermeil setting honors the pearl''s luminosity without overwhelming it. Appropriate for every occasion from boardroom to celebration, these earrings are an investment in quiet elegance. A meaningful piece for anyone who values substance over flash.', ARRAY['Freshwater Pearl', '14K Gold Vermeil', 'Surgical steel posts'], ARRAY['https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&h=800&fit=crop&q=80'], ARRAY['bestseller'], 4.9, 234, TRUE, FALSE, TRUE, TRUE),

('divine-protection-jewelry-set', 'Divine Protection Jewelry Set', 298.00, 378.00, 'Jewelry Sets', ARRAY['Protection', 'Evil Eye'], 'Mixed protective stones', 'Complete energetic protection and spiritual armor. Guardianship across all dimensions.', 'Premium protective jewelry set with evil eye, black tourmaline, and lapis lazuli pieces.', 'For those who practice serious spiritual protection work, this comprehensive set ensures your entire energetic field is tended with intention. Included: a lapis lazuli and enamel evil eye necklace, a black tourmaline protective bracelet, and matching statement earrings with protective symbols. Each piece is crafted in 14K gold plating with premium stones. Wear the complete set during challenging periods, or mix and match as your intuition guides. A powerful offering for serious practitioners, or an exceptional gift for someone navigating major life transitions. Rooted in ancient protection traditions, expressed through contemporary luxury.', ARRAY['Lapis Lazuli', 'Black Tourmaline', 'Enamel', '14K Gold-plated sterling silver', 'Adjustable closures'], ARRAY['https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=800&h=800&fit=crop&q=80', 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=800&h=800&fit=crop&q=80'], ARRAY['bestseller'], 4.9, 198, TRUE, FALSE, TRUE, TRUE);

-- ============================================
-- INSERT REVIEWS (10 total)
-- ============================================
INSERT INTO public.reviews (product_id, author, rating, text, verified)
SELECT id, 'Sarah M.', 5, 'The Moonlit Guardian bracelet is absolutely beautiful. I''ve been wearing it daily for three months and it feels like part of my spiritual practice. The quality is exceptional.', TRUE
FROM public.products WHERE slug = 'moonlit-guardian-bracelet'
UNION ALL
SELECT id, 'James T.', 5, 'Bought the Celestial Shield pendant as an engagement gift. The presentation was stunning and my fiancée hasn''t taken it off. Worth every penny.', TRUE
FROM public.products WHERE slug = 'celestial-shield-pendant'
UNION ALL
SELECT id, 'Michelle L.', 4, 'Love the rose quartz earrings. They''re delicate and the quality is evident. Shipping was fast too.', TRUE
FROM public.products WHERE slug = 'whisper-of-rose-quartz-earrings'
UNION ALL
SELECT id, 'David K.', 5, 'The Eternal Bond ring exceeded my expectations. The diamond is brilliant and the craftsmanship is remarkable. Customer service was exceptional.', TRUE
FROM public.products WHERE slug = 'eternal-bond-ring'
UNION ALL
SELECT id, 'Elena G.', 5, 'Temple of Light set is perfect. I wear the pieces together and separately depending on the day. The intention behind the collection is palpable.', TRUE
FROM public.products WHERE slug = 'temple-of-light-jewelry-set'
UNION ALL
SELECT id, 'Marcus D.', 4, 'The Evil Eye necklace arrived quickly and securely packaged. Beautiful piece. A little pricier than expected but you get what you pay for.', TRUE
FROM public.products WHERE slug = 'sacred-eye-charm-necklace'
UNION ALL
SELECT id, 'Priya S.', 5, 'I purchased the Divine Protection set during a difficult transition in my life. The quality, intention, and beauty of these pieces gave me real comfort. Highly recommend.', TRUE
FROM public.products WHERE slug = 'divine-protection-jewelry-set'
UNION ALL
SELECT id, 'Thomas R.', 5, 'The amber necklace is stunning. Each piece is unique and the oxidized silver setting is perfect. Feels like wearable art.', TRUE
FROM public.products WHERE slug = 'amber-solstice-necklace'
UNION ALL
SELECT id, 'Jasmine W.', 5, 'Pearl of Wisdom earrings are my new signature piece. Simple, elegant, and the quality is obvious. Investment jewelry.', TRUE
FROM public.products WHERE slug = 'pearl-of-wisdom-earrings'
UNION ALL
SELECT id, 'Christopher N.', 4, 'Beautiful work. I bought the Tree of Life pendant for my daughter''s birthday. She adores it. Great gift option.', TRUE
FROM public.products WHERE slug = 'serenity-tree-of-life-pendant';

-- ============================================
-- MAKE FIRST USER ADMIN (run after signup)
-- Replace 'your-email@example.com' with your admin email
-- ============================================
-- UPDATE public.profiles SET role = 'admin' WHERE email = 'your-email@example.com';
